server:
  port: 8080

#spring:
 # ai:
  #  openai:
   #   api-key: ${OPENAI_API_KEY}
    #  chat:
     #   options:
      #    model: gpt-4.1-mini
       #   temperature: 0.2

spring:
  ai:
    model:
      chat: ollama
      embedding: ollama

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.2
      embedding:
        options:
          model: nomic-embed-text-v2-moe
  
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: product_manuals
      local-datacenter: datacenter1
      schema-action: none
# Astra DB configuration (Cassandra + Secure Connect Bundle)
#astra:
 # bundle-path: secure-connect-product_manuals.zip
  #username: cassandra
  #password: cassandra
  #keyspace: product_manuals
